version: '3.8'
services:
  web:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - api
    restart: always
  api:
    build: ./backend
    ports:
      - "8080:8080"
    restart: always